# -*- coding: utf-8 -*-
"""Google-play-scraper-Linkedin.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cqw4qyBL75_cvxvPAo0_JqdQw6WvlTCI

# Scraping Aplikasi Linkedin Singapura menggunakan Google-Play-Scraper
"""

pd.set_option('display.max_colwidth', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

!pip install google-play-scraper

from google_play_scraper import Sort, reviews_all
import pandas as pd

# Scrape reviews from the LinkedIn app
result = reviews_all(
    'com.linkedin.android',
    sleep_milliseconds=0,  # defaults to 0
    lang='en',              # defaults to 'en'
    country='sg',          # defaults to 'us'
    sort=Sort.NEWEST,      # defaults to Sort.MOST_RELEVANT
)

# Create a DataFrame
df = pd.DataFrame(result)

# Save to CSV with escape character and quote character
df.to_csv('linkedin_reviews_singapore.csv', index=False, escapechar='\\', quoting=1)  # quoting=1 corresponds to QUOTE_ALL

len(df)

# limit 10.000 data and resave to csv
df_limited = df.head(10000)
df_limited.to_csv('linkedin_reviews_singapore_limited.csv', index=False, escapechar='\\', quoting=1)

df.head(10000)